### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by XavierMFC** [myeungun/SAR-water-segmentation#1]
hello!
the permission is needed in the dataset's link  you provide ~
if possible, can you share it~
thank you !

**Comment by myeungun** [comment]
Hello!
You have granted the requested permission.
Thank you :-)

**Comment by XavierMFC** [comment]
thx~

**Comment by Dawn-bin** [comment]
hi, I need this dataset. Can I get access permission? thank U ! 🙏
